### ISSUE TITLE
extended precision/calling from C/C++

### ISSUE THREAD

**Issue by tcaduser** [scott-maddox/fdint#19]
Hi,

Is it possible to get these routines in 128 floating point precision?

I am new to cython, is there a good tutorial on how to compile your work (or cython in general) so it is callable from C/C++?

Regards,

Juan

**Comment by scott-maddox** [comment]
Hi Juan,

I wouldn't suggest trying to call into this library from C/C++. Instead, I would suggest following the linked papers and, if you like, referencing the Cython source code or Fukushima's original FORTRAN source code, in order to port to C/C++. This should be pretty trivial, and should not take more than a day or two to get the core functionality.

You could even alter the code generation scripts in the `scripts` folder, in order to automate much of the porting, much like I did when porting to Cython.

As for 128-bit precision, that would require recalculating all of the constants. If you want to undertake this, I recommend reading the original papers by Fukushima (see the [README](https://github.com/scott-maddox/fdint/blob/master/README.rst)).

Best of luck!
